import "../css/style.css";

import type { Metadata } from "next";
import { Inter, Tajawal } from "next/font/google";
import Header from "@/app/components/ui/header";
import Banner from "@/app/components/banner";
import "aos/dist/aos.css";
import { Analytics } from "@vercel/analytics/react";
import MainToastContainer from "../components/MainToastContainer";
import { Locale, i18n } from "@/i18n.config";
import { getDictionary } from "@/lib/dictionary";
import { inDevEnvironment } from "../helpers/devMode";
import AuthProvider from "../components/providers/AuthProvider";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/ThemeProvider";
// const inter = Inter({
//   subsets: ["latin"],
//   variable: "--font-inter",
//   display: "swap",
// });

const tajawal = Tajawal({
  subsets: ["latin", "arabic"],
  weight: ["200", "300", "400", "500", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Lands app",
  description: "Generated by create next app",
};
export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default async function RootLayout({
  children,
  params: { lang },
}: Readonly<{
  children: React.ReactNode;
  params: { lang: Locale };
}>) {
  const {
    nav,
    theme,
    authentication: { sign_in, sign_up },
  } = await getDictionary(lang);
  const linkItems = [
    // { link: '#', name: 'Services' },
    { url: `/${lang}/reals/apartments`, text: nav.appartments },
    { url: `/${lang}/reals/lands`, text: nav.lands },
    { url: `/${lang}/real/create`, text: nav.create_ad },
  ];
  const dir = lang === "ar" ? "rtl" : "ltr";
  return (
    <html lang={lang} dir={dir}>
      <body className={cn("antialiased bg-background", tajawal.className)}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AuthProvider>
            <div className="flex flex-col min-h-screen overflow-hidden supports-[overflow:clip]:overflow-clip">
              <Header
                t={{ theme }}
                linkItems={linkItems}
                sign_in={sign_in}
                sign_up={sign_up}
                lang={lang}
              />
              {children}
              <MainToastContainer />
              <Banner />
            </div>
            {inDevEnvironment === false && <Analytics />}
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
