import "../css/style.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/app/components/ui/header";
import Banner from "@/app/components/banner";
import "aos/dist/aos.css";
import { Analytics } from "@vercel/analytics/react";
import MainToastContainer from "../components/MainToastContainer";
import { Locale, i18n } from "@/i18n.config";
import { getDictionary } from "@/lib/dictionary";
import { inDevEnvironment } from "../helpers/devMode";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Lands app",
  description: "Generated by create next app",
};
export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default async function RootLayout({
  children,
  params: { lang },
}: {
  children: React.ReactNode;
  params: { lang: Locale };
}) {
  const {
    nav,
    authentication: { sign_in, sign_up },
  } = await getDictionary(lang);
  const linkItems = [
    // { link: '#', name: 'Services' },
    { url: `/${lang}/reals/apartments`, text: nav.appartments },
    { url: `/${lang}/reals/lands`, text: nav.lands },
    { url: `/${lang}/real/create`, text: nav.create_ad },
  ];
  const dir = lang === "ar" ? "rtl" : "ltr";
  return (
    <html lang={lang} dir={dir}>
      <body
        className={`${inter.variable} font-inter antialiased bg-white text-gray-900 tracking-tight`}
      >
        <div className="flex flex-col min-h-screen overflow-hidden supports-[overflow:clip]:overflow-clip">
          <Header
            linkItems={linkItems}
            sign_in={sign_in}
            sign_up={sign_up}
            lang={lang}
          />
          {children}
          <MainToastContainer />
          <Banner />
        </div>
        {inDevEnvironment === false && <Analytics />}
      </body>
    </html>
  );
}
